name: Create Release

on:
  push:
    tags:
      - 'v*' # Срабатывает при пуше тега, например v1.0.0, v2.1.3

permissions:
  contents: write # Нужно для создания релиза

jobs:
  build_release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: windows
            arch: amd64
          - os: android
            arch: arm64
          - os: darwin
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Build Client
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          filename="client-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "android" ]; then
            filename="libvkturn-client-${{ matrix.arch }}.so"
          elif [ "${{ matrix.os }}" = "windows" ]; then
            filename="${filename}.exe"
          fi
          go build -v -ldflags "-s -w -checklinkname=0" -trimpath -o "dist/${filename}" ./client

      - name: Build Server
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          filename="server-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "android" ]; then
            filename="libvkturn-server-${{ matrix.arch }}.so"
          elif [ "${{ matrix.os }}" = "windows" ]; then
            filename="${filename}.exe"
          fi
          go build -v -ldflags "-s -w -checklinkname=0" -trimpath -o "dist/${filename}" ./server

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
